//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace DHQR.DataAccess.Entities
{
    public partial class DHQREntities : ObjectContext
    {
        public const string ConnectionString = "name=DHQREntities";
        public const string ContainerName = "DHQREntities";
    
        #region Constructors
    
        public DHQREntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public DHQREntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public DHQREntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // 创建代理需要使用 ProxyDataContractResolver 和
            // 可允许延迟加载，这可以在序列化期间展开加载图。
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet 属性
    
        public ObjectSet<AttachmentInfo> AttachmentInfos
        {
            get { return _attachmentInfos  ?? (_attachmentInfos = CreateObjectSet<AttachmentInfo>("AttachmentInfos")); }
        }
        private ObjectSet<AttachmentInfo> _attachmentInfos;
    
        public ObjectSet<BaseEnum> BaseEnums
        {
            get { return _baseEnums  ?? (_baseEnums = CreateObjectSet<BaseEnum>("BaseEnums")); }
        }
        private ObjectSet<BaseEnum> _baseEnums;
    
        public ObjectSet<CarCheckKey> CarCheckKeys
        {
            get { return _carCheckKeys  ?? (_carCheckKeys = CreateObjectSet<CarCheckKey>("CarCheckKeys")); }
        }
        private ObjectSet<CarCheckKey> _carCheckKeys;
    
        public ObjectSet<CarRunKey> CarRunKeys
        {
            get { return _carRunKeys  ?? (_carRunKeys = CreateObjectSet<CarRunKey>("CarRunKeys")); }
        }
        private ObjectSet<CarRunKey> _carRunKeys;
    
        public ObjectSet<CoReturnLine> CoReturnLines
        {
            get { return _coReturnLines  ?? (_coReturnLines = CreateObjectSet<CoReturnLine>("CoReturnLines")); }
        }
        private ObjectSet<CoReturnLine> _coReturnLines;
    
        public ObjectSet<CoReturn> CoReturns
        {
            get { return _coReturns  ?? (_coReturns = CreateObjectSet<CoReturn>("CoReturns")); }
        }
        private ObjectSet<CoReturn> _coReturns;
    
        public ObjectSet<DeliveryWarning> DeliveryWarnings
        {
            get { return _deliveryWarnings  ?? (_deliveryWarnings = CreateObjectSet<DeliveryWarning>("DeliveryWarnings")); }
        }
        private ObjectSet<DeliveryWarning> _deliveryWarnings;
    
        public ObjectSet<Department> Departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<Department>("Departments")); }
        }
        private ObjectSet<Department> _departments;
    
        public ObjectSet<DistAttachmentInfo> DistAttachmentInfos
        {
            get { return _distAttachmentInfos  ?? (_distAttachmentInfos = CreateObjectSet<DistAttachmentInfo>("DistAttachmentInfos")); }
        }
        private ObjectSet<DistAttachmentInfo> _distAttachmentInfos;
    
        public ObjectSet<DistCarCheck> DistCarChecks
        {
            get { return _distCarChecks  ?? (_distCarChecks = CreateObjectSet<DistCarCheck>("DistCarChecks")); }
        }
        private ObjectSet<DistCarCheck> _distCarChecks;
    
        public ObjectSet<DistCarRunLine> DistCarRunLines
        {
            get { return _distCarRunLines  ?? (_distCarRunLines = CreateObjectSet<DistCarRunLine>("DistCarRunLines")); }
        }
        private ObjectSet<DistCarRunLine> _distCarRunLines;
    
        public ObjectSet<DistCust> DistCusts
        {
            get { return _distCusts  ?? (_distCusts = CreateObjectSet<DistCust>("DistCusts")); }
        }
        private ObjectSet<DistCust> _distCusts;
    
        public ObjectSet<DistDlvman> DistDlvmans
        {
            get { return _distDlvmans  ?? (_distDlvmans = CreateObjectSet<DistDlvman>("DistDlvmans")); }
        }
        private ObjectSet<DistDlvman> _distDlvmans;
    
        public ObjectSet<DistFileLine> DistFileLines
        {
            get { return _distFileLines  ?? (_distFileLines = CreateObjectSet<DistFileLine>("DistFileLines")); }
        }
        private ObjectSet<DistFileLine> _distFileLines;
    
        public ObjectSet<DistRecordLog> DistRecordLogs
        {
            get { return _distRecordLogs  ?? (_distRecordLogs = CreateObjectSet<DistRecordLog>("DistRecordLogs")); }
        }
        private ObjectSet<DistRecordLog> _distRecordLogs;
    
        public ObjectSet<ExceptionLog> ExceptionLogs
        {
            get { return _exceptionLogs  ?? (_exceptionLogs = CreateObjectSet<ExceptionLog>("ExceptionLogs")); }
        }
        private ObjectSet<ExceptionLog> _exceptionLogs;
    
        public ObjectSet<GisCustPois> GisCustPois
        {
            get { return _gisCustPois  ?? (_gisCustPois = CreateObjectSet<GisCustPois>("GisCustPois")); }
        }
        private ObjectSet<GisCustPois> _gisCustPois;
    
        public ObjectSet<GisLastLocrecord> GisLastLocrecords
        {
            get { return _gisLastLocrecords  ?? (_gisLastLocrecords = CreateObjectSet<GisLastLocrecord>("GisLastLocrecords")); }
        }
        private ObjectSet<GisLastLocrecord> _gisLastLocrecords;
    
        public ObjectSet<LdmDisItem> LdmDisItems
        {
            get { return _ldmDisItems  ?? (_ldmDisItems = CreateObjectSet<LdmDisItem>("LdmDisItems")); }
        }
        private ObjectSet<LdmDisItem> _ldmDisItems;
    
        public ObjectSet<LdmDistCar> LdmDistCars
        {
            get { return _ldmDistCars  ?? (_ldmDistCars = CreateObjectSet<LdmDistCar>("LdmDistCars")); }
        }
        private ObjectSet<LdmDistCar> _ldmDistCars;
    
        public ObjectSet<LdmDistLine> LdmDistLines
        {
            get { return _ldmDistLines  ?? (_ldmDistLines = CreateObjectSet<LdmDistLine>("LdmDistLines")); }
        }
        private ObjectSet<LdmDistLine> _ldmDistLines;
    
        public ObjectSet<LdmDist> LdmDists
        {
            get { return _ldmDists  ?? (_ldmDists = CreateObjectSet<LdmDist>("LdmDists")); }
        }
        private ObjectSet<LdmDist> _ldmDists;
    
        public ObjectSet<LoginLog> LoginLogs
        {
            get { return _loginLogs  ?? (_loginLogs = CreateObjectSet<LoginLog>("LoginLogs")); }
        }
        private ObjectSet<LoginLog> _loginLogs;
    
        public ObjectSet<LogKey> LogKeys
        {
            get { return _logKeys  ?? (_logKeys = CreateObjectSet<LogKey>("LogKeys")); }
        }
        private ObjectSet<LogKey> _logKeys;
    
        public ObjectSet<Menu> Menus
        {
            get { return _menus  ?? (_menus = CreateObjectSet<Menu>("Menus")); }
        }
        private ObjectSet<Menu> _menus;
    
        public ObjectSet<ModuleRole> ModuleRoles
        {
            get { return _moduleRoles  ?? (_moduleRoles = CreateObjectSet<ModuleRole>("ModuleRoles")); }
        }
        private ObjectSet<ModuleRole> _moduleRoles;
    
        public ObjectSet<ModuleRoleToModule> ModuleRoleToModules
        {
            get { return _moduleRoleToModules  ?? (_moduleRoleToModules = CreateObjectSet<ModuleRoleToModule>("ModuleRoleToModules")); }
        }
        private ObjectSet<ModuleRoleToModule> _moduleRoleToModules;
    
        public ObjectSet<Module> Modules
        {
            get { return _modules  ?? (_modules = CreateObjectSet<Module>("Modules")); }
        }
        private ObjectSet<Module> _modules;
    
        public ObjectSet<Region> Regions
        {
            get { return _regions  ?? (_regions = CreateObjectSet<Region>("Regions")); }
        }
        private ObjectSet<Region> _regions;
    
        public ObjectSet<ReOrderKey> ReOrderKeys
        {
            get { return _reOrderKeys  ?? (_reOrderKeys = CreateObjectSet<ReOrderKey>("ReOrderKeys")); }
        }
        private ObjectSet<ReOrderKey> _reOrderKeys;
    
        public ObjectSet<RoleToAction> RoleToActions
        {
            get { return _roleToActions  ?? (_roleToActions = CreateObjectSet<RoleToAction>("RoleToActions")); }
        }
        private ObjectSet<RoleToAction> _roleToActions;
    
        public ObjectSet<ServiceCallLog> ServiceCallLogs
        {
            get { return _serviceCallLogs  ?? (_serviceCallLogs = CreateObjectSet<ServiceCallLog>("ServiceCallLogs")); }
        }
        private ObjectSet<ServiceCallLog> _serviceCallLogs;
    
        public ObjectSet<ServiceExceptionLog> ServiceExceptionLogs
        {
            get { return _serviceExceptionLogs  ?? (_serviceExceptionLogs = CreateObjectSet<ServiceExceptionLog>("ServiceExceptionLogs")); }
        }
        private ObjectSet<ServiceExceptionLog> _serviceExceptionLogs;
    
        public ObjectSet<UserFastModule> UserFastModules
        {
            get { return _userFastModules  ?? (_userFastModules = CreateObjectSet<UserFastModule>("UserFastModules")); }
        }
        private ObjectSet<UserFastModule> _userFastModules;
    
        public ObjectSet<UserModuleRole> UserModuleRoles
        {
            get { return _userModuleRoles  ?? (_userModuleRoles = CreateObjectSet<UserModuleRole>("UserModuleRoles")); }
        }
        private ObjectSet<UserModuleRole> _userModuleRoles;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<AppVersion> AppVersions
        {
            get { return _appVersions  ?? (_appVersions = CreateObjectSet<AppVersion>("AppVersions")); }
        }
        private ObjectSet<AppVersion> _appVersions;
    
        public ObjectSet<WeiXinArticle> WeiXinArticles
        {
            get { return _weiXinArticles  ?? (_weiXinArticles = CreateObjectSet<WeiXinArticle>("WeiXinArticles")); }
        }
        private ObjectSet<WeiXinArticle> _weiXinArticles;
    
        public ObjectSet<WeiXinArticlesType> WeiXinArticlesTypes
        {
            get { return _weiXinArticlesTypes  ?? (_weiXinArticlesTypes = CreateObjectSet<WeiXinArticlesType>("WeiXinArticlesTypes")); }
        }
        private ObjectSet<WeiXinArticlesType> _weiXinArticlesTypes;
    
        public ObjectSet<WeiXinCustomUrl> WeiXinCustomUrls
        {
            get { return _weiXinCustomUrls  ?? (_weiXinCustomUrls = CreateObjectSet<WeiXinCustomUrl>("WeiXinCustomUrls")); }
        }
        private ObjectSet<WeiXinCustomUrl> _weiXinCustomUrls;
    
        public ObjectSet<WeiXinFirstIn> WeiXinFirstIns
        {
            get { return _weiXinFirstIns  ?? (_weiXinFirstIns = CreateObjectSet<WeiXinFirstIn>("WeiXinFirstIns")); }
        }
        private ObjectSet<WeiXinFirstIn> _weiXinFirstIns;
    
        public ObjectSet<WeiXinKeyWord> WeiXinKeyWords
        {
            get { return _weiXinKeyWords  ?? (_weiXinKeyWords = CreateObjectSet<WeiXinKeyWord>("WeiXinKeyWords")); }
        }
        private ObjectSet<WeiXinKeyWord> _weiXinKeyWords;
    
        public ObjectSet<WeiXinLogistic> WeiXinLogistics
        {
            get { return _weiXinLogistics  ?? (_weiXinLogistics = CreateObjectSet<WeiXinLogistic>("WeiXinLogistics")); }
        }
        private ObjectSet<WeiXinLogistic> _weiXinLogistics;
    
        public ObjectSet<WeiXinMenu> WeiXinMenus
        {
            get { return _weiXinMenus  ?? (_weiXinMenus = CreateObjectSet<WeiXinMenu>("WeiXinMenus")); }
        }
        private ObjectSet<WeiXinMenu> _weiXinMenus;
    
        public ObjectSet<WeiXinPicMsgDetail> WeiXinPicMsgDetails
        {
            get { return _weiXinPicMsgDetails  ?? (_weiXinPicMsgDetails = CreateObjectSet<WeiXinPicMsgDetail>("WeiXinPicMsgDetails")); }
        }
        private ObjectSet<WeiXinPicMsgDetail> _weiXinPicMsgDetails;
    
        public ObjectSet<WeiXinPicMsgMatser> WeiXinPicMsgMatsers
        {
            get { return _weiXinPicMsgMatsers  ?? (_weiXinPicMsgMatsers = CreateObjectSet<WeiXinPicMsgMatser>("WeiXinPicMsgMatsers")); }
        }
        private ObjectSet<WeiXinPicMsgMatser> _weiXinPicMsgMatsers;
    
        public ObjectSet<WeiXinSource> WeiXinSources
        {
            get { return _weiXinSources  ?? (_weiXinSources = CreateObjectSet<WeiXinSource>("WeiXinSources")); }
        }
        private ObjectSet<WeiXinSource> _weiXinSources;
    
        public ObjectSet<WeiXinSysType> WeiXinSysTypes
        {
            get { return _weiXinSysTypes  ?? (_weiXinSysTypes = CreateObjectSet<WeiXinSysType>("WeiXinSysTypes")); }
        }
        private ObjectSet<WeiXinSysType> _weiXinSysTypes;
    
        public ObjectSet<WeiXinTriggerInfo> WeiXinTriggerInfos
        {
            get { return _weiXinTriggerInfos  ?? (_weiXinTriggerInfos = CreateObjectSet<WeiXinTriggerInfo>("WeiXinTriggerInfos")); }
        }
        private ObjectSet<WeiXinTriggerInfo> _weiXinTriggerInfos;
    
        public ObjectSet<WeiXinUser> WeiXinUsers
        {
            get { return _weiXinUsers  ?? (_weiXinUsers = CreateObjectSet<WeiXinUser>("WeiXinUsers")); }
        }
        private ObjectSet<WeiXinUser> _weiXinUsers;
    
        public ObjectSet<WeiXinUserType> WeiXinUserTypes
        {
            get { return _weiXinUserTypes  ?? (_weiXinUserTypes = CreateObjectSet<WeiXinUserType>("WeiXinUserTypes")); }
        }
        private ObjectSet<WeiXinUserType> _weiXinUserTypes;
    
        public ObjectSet<WeiXinUserTypeToModule> WeiXinUserTypeToModules
        {
            get { return _weiXinUserTypeToModules  ?? (_weiXinUserTypeToModules = CreateObjectSet<WeiXinUserTypeToModule>("WeiXinUserTypeToModules")); }
        }
        private ObjectSet<WeiXinUserTypeToModule> _weiXinUserTypeToModules;
    
        public ObjectSet<DistRut> DistRuts
        {
            get { return _distRuts  ?? (_distRuts = CreateObjectSet<DistRut>("DistRuts")); }
        }
        private ObjectSet<DistRut> _distRuts;
    
        public ObjectSet<DistCarRun> DistCarRuns
        {
            get { return _distCarRuns  ?? (_distCarRuns = CreateObjectSet<DistCarRun>("DistCarRuns")); }
        }
        private ObjectSet<DistCarRun> _distCarRuns;
    
        public ObjectSet<EntranceCard> EntranceCards
        {
            get { return _entranceCards  ?? (_entranceCards = CreateObjectSet<EntranceCard>("EntranceCards")); }
        }
        private ObjectSet<EntranceCard> _entranceCards;
    
        public ObjectSet<WeiXinUserGroup> WeiXinUserGroups
        {
            get { return _weiXinUserGroups  ?? (_weiXinUserGroups = CreateObjectSet<WeiXinUserGroup>("WeiXinUserGroups")); }
        }
        private ObjectSet<WeiXinUserGroup> _weiXinUserGroups;
    
        public ObjectSet<WeiXinUserInfo> WeiXinUserInfos
        {
            get { return _weiXinUserInfos  ?? (_weiXinUserInfos = CreateObjectSet<WeiXinUserInfo>("WeiXinUserInfos")); }
        }
        private ObjectSet<WeiXinUserInfo> _weiXinUserInfos;
    
        public ObjectSet<WeiXinMedia> WeiXinMedias
        {
            get { return _weiXinMedias  ?? (_weiXinMedias = CreateObjectSet<WeiXinMedia>("WeiXinMedias")); }
        }
        private ObjectSet<WeiXinMedia> _weiXinMedias;
    
        public ObjectSet<WeiXinMassMsg> WeiXinMassMsgs
        {
            get { return _weiXinMassMsgs  ?? (_weiXinMassMsgs = CreateObjectSet<WeiXinMassMsg>("WeiXinMassMsgs")); }
        }
        private ObjectSet<WeiXinMassMsg> _weiXinMassMsgs;
    
        public ObjectSet<WeiXinSysUrl> WeiXinSysUrls
        {
            get { return _weiXinSysUrls  ?? (_weiXinSysUrls = CreateObjectSet<WeiXinSysUrl>("WeiXinSysUrls")); }
        }
        private ObjectSet<WeiXinSysUrl> _weiXinSysUrls;
    
        public ObjectSet<WeiXinMassMsgHist> WeiXinMassMsgHists
        {
            get { return _weiXinMassMsgHists  ?? (_weiXinMassMsgHists = CreateObjectSet<WeiXinMassMsgHist>("WeiXinMassMsgHists")); }
        }
        private ObjectSet<WeiXinMassMsgHist> _weiXinMassMsgHists;
    
        public ObjectSet<WeiXinApp> WeiXinApps
        {
            get { return _weiXinApps  ?? (_weiXinApps = CreateObjectSet<WeiXinApp>("WeiXinApps")); }
        }
        private ObjectSet<WeiXinApp> _weiXinApps;
    
        public ObjectSet<GlobalConfiguration> GlobalConfigurations
        {
            get { return _globalConfigurations  ?? (_globalConfigurations = CreateObjectSet<GlobalConfiguration>("GlobalConfigurations")); }
        }
        private ObjectSet<GlobalConfiguration> _globalConfigurations;
    
        public ObjectSet<CoTempReturn> CoTempReturns
        {
            get { return _coTempReturns  ?? (_coTempReturns = CreateObjectSet<CoTempReturn>("CoTempReturns")); }
        }
        private ObjectSet<CoTempReturn> _coTempReturns;
    
        public ObjectSet<CoTemp> CoTemps
        {
            get { return _coTemps  ?? (_coTemps = CreateObjectSet<CoTemp>("CoTemps")); }
        }
        private ObjectSet<CoTemp> _coTemps;
    
        public ObjectSet<Retailer> Retailers
        {
            get { return _retailers  ?? (_retailers = CreateObjectSet<Retailer>("Retailers")); }
        }
        private ObjectSet<Retailer> _retailers;

        #endregion

    }
}
