//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    public partial class DeliveryWarning: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string DIST_NUM
        {
            get { return _dIST_NUM; }
            set
            {
                if (_dIST_NUM != value)
                {
                    _dIST_NUM = value;
                    OnPropertyChanged("DIST_NUM");
                }
            }
        }
        private string _dIST_NUM;
    
        [DataMember]
        public string CO_NUM
        {
            get { return _cO_NUM; }
            set
            {
                if (_cO_NUM != value)
                {
                    _cO_NUM = value;
                    OnPropertyChanged("CO_NUM");
                }
            }
        }
        private string _cO_NUM;
    
        [DataMember]
        public Nullable<decimal> Longitude
        {
            get { return _longitude; }
            set
            {
                if (_longitude != value)
                {
                    _longitude = value;
                    OnPropertyChanged("Longitude");
                }
            }
        }
        private Nullable<decimal> _longitude;
    
        [DataMember]
        public Nullable<decimal> Latitude
        {
            get { return _latitude; }
            set
            {
                if (_latitude != value)
                {
                    _latitude = value;
                    OnPropertyChanged("Latitude");
                }
            }
        }
        private Nullable<decimal> _latitude;
    
        [DataMember]
        public Nullable<decimal> RealLongitude
        {
            get { return _realLongitude; }
            set
            {
                if (_realLongitude != value)
                {
                    _realLongitude = value;
                    OnPropertyChanged("RealLongitude");
                }
            }
        }
        private Nullable<decimal> _realLongitude;
    
        [DataMember]
        public Nullable<decimal> RealLatitude
        {
            get { return _realLatitude; }
            set
            {
                if (_realLatitude != value)
                {
                    _realLatitude = value;
                    OnPropertyChanged("RealLatitude");
                }
            }
        }
        private Nullable<decimal> _realLatitude;
    
        [DataMember]
        public System.DateTime DeliveryTime
        {
            get { return _deliveryTime; }
            set
            {
                if (_deliveryTime != value)
                {
                    _deliveryTime = value;
                    OnPropertyChanged("DeliveryTime");
                }
            }
        }
        private System.DateTime _deliveryTime;
    
        [DataMember]
        public string Reason
        {
            get { return _reason; }
            set
            {
                if (_reason != value)
                {
                    _reason = value;
                    OnPropertyChanged("Reason");
                }
            }
        }
        private string _reason;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
