//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    public partial class DistCarRunLine: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string INFO_NUM
        {
            get { return _iNFO_NUM; }
            set
            {
                if (_iNFO_NUM != value)
                {
                    _iNFO_NUM = value;
                    OnPropertyChanged("INFO_NUM");
                }
            }
        }
        private string _iNFO_NUM;
    
        [DataMember]
        public int LINE_ID
        {
            get { return _lINE_ID; }
            set
            {
                if (_lINE_ID != value)
                {
                    _lINE_ID = value;
                    OnPropertyChanged("LINE_ID");
                }
            }
        }
        private int _lINE_ID;
    
        [DataMember]
        public string COST_TYPE
        {
            get { return _cOST_TYPE; }
            set
            {
                if (_cOST_TYPE != value)
                {
                    _cOST_TYPE = value;
                    OnPropertyChanged("COST_TYPE");
                }
            }
        }
        private string _cOST_TYPE;
    
        [DataMember]
        public string FUEL_TYPE
        {
            get { return _fUEL_TYPE; }
            set
            {
                if (_fUEL_TYPE != value)
                {
                    _fUEL_TYPE = value;
                    OnPropertyChanged("FUEL_TYPE");
                }
            }
        }
        private string _fUEL_TYPE;
    
        [DataMember]
        public Nullable<decimal> LITRE_SUM
        {
            get { return _lITRE_SUM; }
            set
            {
                if (_lITRE_SUM != value)
                {
                    _lITRE_SUM = value;
                    OnPropertyChanged("LITRE_SUM");
                }
            }
        }
        private Nullable<decimal> _lITRE_SUM;
    
        [DataMember]
        public Nullable<decimal> FUEL_PRI
        {
            get { return _fUEL_PRI; }
            set
            {
                if (_fUEL_PRI != value)
                {
                    _fUEL_PRI = value;
                    OnPropertyChanged("FUEL_PRI");
                }
            }
        }
        private Nullable<decimal> _fUEL_PRI;
    
        [DataMember]
        public decimal AMT
        {
            get { return _aMT; }
            set
            {
                if (_aMT != value)
                {
                    _aMT = value;
                    OnPropertyChanged("AMT");
                }
            }
        }
        private decimal _aMT;
    
        [DataMember]
        public string INV_NUM
        {
            get { return _iNV_NUM; }
            set
            {
                if (_iNV_NUM != value)
                {
                    _iNV_NUM = value;
                    OnPropertyChanged("INV_NUM");
                }
            }
        }
        private string _iNV_NUM;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
