//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    public partial class LdmDistCar: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string CAR_ID
        {
            get { return _cAR_ID; }
            set
            {
                if (_cAR_ID != value)
                {
                    _cAR_ID = value;
                    OnPropertyChanged("CAR_ID");
                }
            }
        }
        private string _cAR_ID;
    
        [DataMember]
        public string CAR_NAME
        {
            get { return _cAR_NAME; }
            set
            {
                if (_cAR_NAME != value)
                {
                    _cAR_NAME = value;
                    OnPropertyChanged("CAR_NAME");
                }
            }
        }
        private string _cAR_NAME;
    
        [DataMember]
        public string CAR_LICENSE
        {
            get { return _cAR_LICENSE; }
            set
            {
                if (_cAR_LICENSE != value)
                {
                    _cAR_LICENSE = value;
                    OnPropertyChanged("CAR_LICENSE");
                }
            }
        }
        private string _cAR_LICENSE;
    
        [DataMember]
        public string DLVMAN_ID
        {
            get { return _dLVMAN_ID; }
            set
            {
                if (_dLVMAN_ID != value)
                {
                    _dLVMAN_ID = value;
                    OnPropertyChanged("DLVMAN_ID");
                }
            }
        }
        private string _dLVMAN_ID;
    
        [DataMember]
        public string DLVMAN_NAME
        {
            get { return _dLVMAN_NAME; }
            set
            {
                if (_dLVMAN_NAME != value)
                {
                    _dLVMAN_NAME = value;
                    OnPropertyChanged("DLVMAN_NAME");
                }
            }
        }
        private string _dLVMAN_NAME;
    
        [DataMember]
        public string DRIVER_ID
        {
            get { return _dRIVER_ID; }
            set
            {
                if (_dRIVER_ID != value)
                {
                    _dRIVER_ID = value;
                    OnPropertyChanged("DRIVER_ID");
                }
            }
        }
        private string _dRIVER_ID;
    
        [DataMember]
        public string DRIVER_NAME
        {
            get { return _dRIVER_NAME; }
            set
            {
                if (_dRIVER_NAME != value)
                {
                    _dRIVER_NAME = value;
                    OnPropertyChanged("DRIVER_NAME");
                }
            }
        }
        private string _dRIVER_NAME;
    
        [DataMember]
        public string IS_MRB
        {
            get { return _iS_MRB; }
            set
            {
                if (_iS_MRB != value)
                {
                    _iS_MRB = value;
                    OnPropertyChanged("IS_MRB");
                }
            }
        }
        private string _iS_MRB;
    
        [DataMember]
        public string COM_ID
        {
            get { return _cOM_ID; }
            set
            {
                if (_cOM_ID != value)
                {
                    _cOM_ID = value;
                    OnPropertyChanged("COM_ID");
                }
            }
        }
        private string _cOM_ID;
    
        [DataMember]
        public string PSW
        {
            get { return _pSW; }
            set
            {
                if (_pSW != value)
                {
                    _pSW = value;
                    OnPropertyChanged("PSW");
                }
            }
        }
        private string _pSW;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
