//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    public partial class LdmDisItem: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string CO_NUM
        {
            get { return _cO_NUM; }
            set
            {
                if (_cO_NUM != value)
                {
                    _cO_NUM = value;
                    OnPropertyChanged("CO_NUM");
                }
            }
        }
        private string _cO_NUM;
    
        [DataMember]
        public string ITEM_ID
        {
            get { return _iTEM_ID; }
            set
            {
                if (_iTEM_ID != value)
                {
                    _iTEM_ID = value;
                    OnPropertyChanged("ITEM_ID");
                }
            }
        }
        private string _iTEM_ID;
    
        [DataMember]
        public string ITEM_NAME
        {
            get { return _iTEM_NAME; }
            set
            {
                if (_iTEM_NAME != value)
                {
                    _iTEM_NAME = value;
                    OnPropertyChanged("ITEM_NAME");
                }
            }
        }
        private string _iTEM_NAME;
    
        [DataMember]
        public decimal PRICE
        {
            get { return _pRICE; }
            set
            {
                if (_pRICE != value)
                {
                    _pRICE = value;
                    OnPropertyChanged("PRICE");
                }
            }
        }
        private decimal _pRICE;
    
        [DataMember]
        public decimal QTY
        {
            get { return _qTY; }
            set
            {
                if (_qTY != value)
                {
                    _qTY = value;
                    OnPropertyChanged("QTY");
                }
            }
        }
        private decimal _qTY;
    
        [DataMember]
        public decimal AMT
        {
            get { return _aMT; }
            set
            {
                if (_aMT != value)
                {
                    _aMT = value;
                    OnPropertyChanged("AMT");
                }
            }
        }
        private decimal _aMT;
    
        [DataMember]
        public string IS_ABNORMAL
        {
            get { return _iS_ABNORMAL; }
            set
            {
                if (_iS_ABNORMAL != value)
                {
                    _iS_ABNORMAL = value;
                    OnPropertyChanged("IS_ABNORMAL");
                }
            }
        }
        private string _iS_ABNORMAL;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
