//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ModuleRole))]
    public partial class RoleToAction: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public System.Guid RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    ChangeTracker.RecordOriginalValue("RoleId", _roleId);
                    if (!IsDeserializing)
                    {
                        if (ModuleRole != null && ModuleRole.Id != value)
                        {
                            ModuleRole = null;
                        }
                    }
                    _roleId = value;
                    OnPropertyChanged("RoleId");
                }
            }
        }
        private System.Guid _roleId;
    
        [DataMember]
        public System.Guid MenuId
        {
            get { return _menuId; }
            set
            {
                if (_menuId != value)
                {
                    _menuId = value;
                    OnPropertyChanged("MenuId");
                }
            }
        }
        private System.Guid _menuId;
    
        [DataMember]
        public string ActionList
        {
            get { return _actionList; }
            set
            {
                if (_actionList != value)
                {
                    _actionList = value;
                    OnPropertyChanged("ActionList");
                }
            }
        }
        private string _actionList;

        #endregion

        #region 导航属性
    
        [DataMember]
        public ModuleRole ModuleRole
        {
            get { return _moduleRole; }
            set
            {
                if (!ReferenceEquals(_moduleRole, value))
                {
                    var previousValue = _moduleRole;
                    _moduleRole = value;
                    FixupModuleRole(previousValue);
                    OnNavigationPropertyChanged("ModuleRole");
                }
            }
        }
        private ModuleRole _moduleRole;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ModuleRole = null;
        }

        #endregion

        #region 关联修复
    
        private void FixupModuleRole(ModuleRole previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RoleToActions.Contains(this))
            {
                previousValue.RoleToActions.Remove(this);
            }
    
            if (ModuleRole != null)
            {
                if (!ModuleRole.RoleToActions.Contains(this))
                {
                    ModuleRole.RoleToActions.Add(this);
                }
    
                RoleId = ModuleRole.Id;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ModuleRole")
                    && (ChangeTracker.OriginalValues["ModuleRole"] == ModuleRole))
                {
                    ChangeTracker.OriginalValues.Remove("ModuleRole");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ModuleRole", previousValue);
                }
                if (ModuleRole != null && !ModuleRole.ChangeTracker.ChangeTrackingEnabled)
                {
                    ModuleRole.StartTracking();
                }
            }
        }

        #endregion

    }
}
