//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    public partial class DistCarRun: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string INFO_NUM
        {
            get { return _iNFO_NUM; }
            set
            {
                if (_iNFO_NUM != value)
                {
                    _iNFO_NUM = value;
                    OnPropertyChanged("INFO_NUM");
                }
            }
        }
        private string _iNFO_NUM;
    
        [DataMember]
        public string REF_TYPE
        {
            get { return _rEF_TYPE; }
            set
            {
                if (_rEF_TYPE != value)
                {
                    _rEF_TYPE = value;
                    OnPropertyChanged("REF_TYPE");
                }
            }
        }
        private string _rEF_TYPE;
    
        [DataMember]
        public string REF_ID
        {
            get { return _rEF_ID; }
            set
            {
                if (_rEF_ID != value)
                {
                    _rEF_ID = value;
                    OnPropertyChanged("REF_ID");
                }
            }
        }
        private string _rEF_ID;
    
        [DataMember]
        public string CAR_ID
        {
            get { return _cAR_ID; }
            set
            {
                if (_cAR_ID != value)
                {
                    _cAR_ID = value;
                    OnPropertyChanged("CAR_ID");
                }
            }
        }
        private string _cAR_ID;
    
        [DataMember]
        public string DLVMAN_ID
        {
            get { return _dLVMAN_ID; }
            set
            {
                if (_dLVMAN_ID != value)
                {
                    _dLVMAN_ID = value;
                    OnPropertyChanged("DLVMAN_ID");
                }
            }
        }
        private string _dLVMAN_ID;
    
        [DataMember]
        public string CRT_DATE
        {
            get { return _cRT_DATE; }
            set
            {
                if (_cRT_DATE != value)
                {
                    _cRT_DATE = value;
                    OnPropertyChanged("CRT_DATE");
                }
            }
        }
        private string _cRT_DATE;
    
        [DataMember]
        public Nullable<decimal> AMT_SUM
        {
            get { return _aMT_SUM; }
            set
            {
                if (_aMT_SUM != value)
                {
                    _aMT_SUM = value;
                    OnPropertyChanged("AMT_SUM");
                }
            }
        }
        private Nullable<decimal> _aMT_SUM;
    
        [DataMember]
        public Nullable<decimal> PRE_MIL
        {
            get { return _pRE_MIL; }
            set
            {
                if (_pRE_MIL != value)
                {
                    _pRE_MIL = value;
                    OnPropertyChanged("PRE_MIL");
                }
            }
        }
        private Nullable<decimal> _pRE_MIL;
    
        [DataMember]
        public Nullable<decimal> THIS_MIL
        {
            get { return _tHIS_MIL; }
            set
            {
                if (_tHIS_MIL != value)
                {
                    _tHIS_MIL = value;
                    OnPropertyChanged("THIS_MIL");
                }
            }
        }
        private Nullable<decimal> _tHIS_MIL;
    
        [DataMember]
        public Nullable<decimal> ACT_MIL
        {
            get { return _aCT_MIL; }
            set
            {
                if (_aCT_MIL != value)
                {
                    _aCT_MIL = value;
                    OnPropertyChanged("ACT_MIL");
                }
            }
        }
        private Nullable<decimal> _aCT_MIL;
    
        [DataMember]
        public string NOTE
        {
            get { return _nOTE; }
            set
            {
                if (_nOTE != value)
                {
                    _nOTE = value;
                    OnPropertyChanged("NOTE");
                }
            }
        }
        private string _nOTE;
    
        [DataMember]
        public int DistYear
        {
            get { return _distYear; }
            set
            {
                if (_distYear != value)
                {
                    _distYear = value;
                    OnPropertyChanged("DistYear");
                }
            }
        }
        private int _distYear;
    
        [DataMember]
        public int DistMonth
        {
            get { return _distMonth; }
            set
            {
                if (_distMonth != value)
                {
                    _distMonth = value;
                    OnPropertyChanged("DistMonth");
                }
            }
        }
        private int _distMonth;
    
        [DataMember]
        public System.DateTime CreateTime
        {
            get { return _createTime; }
            set
            {
                if (_createTime != value)
                {
                    _createTime = value;
                    OnPropertyChanged("CreateTime");
                }
            }
        }
        private System.DateTime _createTime;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
