//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    public partial class DistCarCheck: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string CHECK_ID
        {
            get { return _cHECK_ID; }
            set
            {
                if (_cHECK_ID != value)
                {
                    _cHECK_ID = value;
                    OnPropertyChanged("CHECK_ID");
                }
            }
        }
        private string _cHECK_ID;
    
        [DataMember]
        public string CAR_ID
        {
            get { return _cAR_ID; }
            set
            {
                if (_cAR_ID != value)
                {
                    _cAR_ID = value;
                    OnPropertyChanged("CAR_ID");
                }
            }
        }
        private string _cAR_ID;
    
        [DataMember]
        public string REF_TYPE
        {
            get { return _rEF_TYPE; }
            set
            {
                if (_rEF_TYPE != value)
                {
                    _rEF_TYPE = value;
                    OnPropertyChanged("REF_TYPE");
                }
            }
        }
        private string _rEF_TYPE;
    
        [DataMember]
        public string REF_ID
        {
            get { return _rEF_ID; }
            set
            {
                if (_rEF_ID != value)
                {
                    _rEF_ID = value;
                    OnPropertyChanged("REF_ID");
                }
            }
        }
        private string _rEF_ID;
    
        [DataMember]
        public string ABNORMAL_DETAIL
        {
            get { return _aBNORMAL_DETAIL; }
            set
            {
                if (_aBNORMAL_DETAIL != value)
                {
                    _aBNORMAL_DETAIL = value;
                    OnPropertyChanged("ABNORMAL_DETAIL");
                }
            }
        }
        private string _aBNORMAL_DETAIL;
    
        [DataMember]
        public string ABNORMAL_TYPE
        {
            get { return _aBNORMAL_TYPE; }
            set
            {
                if (_aBNORMAL_TYPE != value)
                {
                    _aBNORMAL_TYPE = value;
                    OnPropertyChanged("ABNORMAL_TYPE");
                }
            }
        }
        private string _aBNORMAL_TYPE;
    
        [DataMember]
        public string CHECK_TIME
        {
            get { return _cHECK_TIME; }
            set
            {
                if (_cHECK_TIME != value)
                {
                    _cHECK_TIME = value;
                    OnPropertyChanged("CHECK_TIME");
                }
            }
        }
        private string _cHECK_TIME;
    
        [DataMember]
        public Nullable<decimal> LONGITUDE
        {
            get { return _lONGITUDE; }
            set
            {
                if (_lONGITUDE != value)
                {
                    _lONGITUDE = value;
                    OnPropertyChanged("LONGITUDE");
                }
            }
        }
        private Nullable<decimal> _lONGITUDE;
    
        [DataMember]
        public Nullable<decimal> LATITUDE
        {
            get { return _lATITUDE; }
            set
            {
                if (_lATITUDE != value)
                {
                    _lATITUDE = value;
                    OnPropertyChanged("LATITUDE");
                }
            }
        }
        private Nullable<decimal> _lATITUDE;
    
        [DataMember]
        public string CHECK_TYPE
        {
            get { return _cHECK_TYPE; }
            set
            {
                if (_cHECK_TYPE != value)
                {
                    _cHECK_TYPE = value;
                    OnPropertyChanged("CHECK_TYPE");
                }
            }
        }
        private string _cHECK_TYPE;
    
        [DataMember]
        public string OPERATE_MODE
        {
            get { return _oPERATE_MODE; }
            set
            {
                if (_oPERATE_MODE != value)
                {
                    _oPERATE_MODE = value;
                    OnPropertyChanged("OPERATE_MODE");
                }
            }
        }
        private string _oPERATE_MODE;
    
        [DataMember]
        public string NOTE
        {
            get { return _nOTE; }
            set
            {
                if (_nOTE != value)
                {
                    _nOTE = value;
                    OnPropertyChanged("NOTE");
                }
            }
        }
        private string _nOTE;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
