//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace DHQR.DataAccess.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ModuleRoleToModule))]
    public partial class Module: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“Id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string Code
        {
            get { return _code; }
            set
            {
                if (_code != value)
                {
                    _code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        private string _code;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public string ControllerName
        {
            get { return _controllerName; }
            set
            {
                if (_controllerName != value)
                {
                    _controllerName = value;
                    OnPropertyChanged("ControllerName");
                }
            }
        }
        private string _controllerName;
    
        [DataMember]
        public string ActionName
        {
            get { return _actionName; }
            set
            {
                if (_actionName != value)
                {
                    _actionName = value;
                    OnPropertyChanged("ActionName");
                }
            }
        }
        private string _actionName;
    
        [DataMember]
        public bool IsMenu
        {
            get { return _isMenu; }
            set
            {
                if (_isMenu != value)
                {
                    _isMenu = value;
                    OnPropertyChanged("IsMenu");
                }
            }
        }
        private bool _isMenu;
    
        [DataMember]
        public string Url
        {
            get { return _url; }
            set
            {
                if (_url != value)
                {
                    _url = value;
                    OnPropertyChanged("Url");
                }
            }
        }
        private string _url;

        #endregion

        #region 导航属性
    
        [DataMember]
        public TrackableCollection<ModuleRoleToModule> ModuleRoleToModules
        {
            get
            {
                if (_moduleRoleToModules == null)
                {
                    _moduleRoleToModules = new TrackableCollection<ModuleRoleToModule>();
                    _moduleRoleToModules.CollectionChanged += FixupModuleRoleToModules;
                }
                return _moduleRoleToModules;
            }
            set
            {
                if (!ReferenceEquals(_moduleRoleToModules, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("当启用 ChangeTracking 时，无法设置 FixupChangeTrackingCollection");
                    }
                    if (_moduleRoleToModules != null)
                    {
                        _moduleRoleToModules.CollectionChanged -= FixupModuleRoleToModules;
                    }
                    _moduleRoleToModules = value;
                    if (_moduleRoleToModules != null)
                    {
                        _moduleRoleToModules.CollectionChanged += FixupModuleRoleToModules;
                    }
                    OnNavigationPropertyChanged("ModuleRoleToModules");
                }
            }
        }
        private TrackableCollection<ModuleRoleToModule> _moduleRoleToModules;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ModuleRoleToModules.Clear();
        }

        #endregion

        #region 关联修复
    
        private void FixupModuleRoleToModules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ModuleRoleToModule item in e.NewItems)
                {
                    item.Module = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ModuleRoleToModules", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ModuleRoleToModule item in e.OldItems)
                {
                    if (ReferenceEquals(item.Module, this))
                    {
                        item.Module = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ModuleRoleToModules", item);
                    }
                }
            }
        }

        #endregion

    }
}
